#!/bin/bash -e

INSTALL_PATH="/opt/under/cryptorescuecore/"
BIN=$(realpath "$INSTALL_PATH"/cryptorescuecore/node_modules/cryptorescuecore-node/bin/cryptorescue-*/bin/)
DATA="$INSTALL_PATH/home/.cryptorescuecore/data"
CONF="$DATA/cryptorescue.conf"

exec "$BIN"/cryptorescue-cli --conf="$CONF" --datadir="$DATA" "$@"
