#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/under/cryptorescuecore/home \
			--quiet --gecos "under cryptorescuecore" cryptorescuecore
		chown -R cryptorescuecore /opt/under/cryptorescuecore/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
